name: email_sender
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.7
  excel: ^2.0.0
  mailer: ^6.0.0
  fluent_ui: ^4.9.2
  system_theme: ^3.1.2
  flutter_acrylic: ^1.1.4
  provider: ^6.1.2
  window_manager: ^0.4.3
  url_launcher: ^6.3.1
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  syncfusion_flutter_xlsio: ^27.2.2
  path_provider: ^2.1.5
  flutter_syntax_view: ^4.1.0
  google_fonts: ^6.2.1
  syncfusion_flutter_datagrid: ^27.2.2
  email_validator: ^3.0.0
  smooth_highlight: ^0.1.2
  recase: ^4.1.0
  desktop_drop: ^0.5.0
  cross_file: ^0.3.4+2
  flutter_svg: ^2.0.15
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
